version: "3.7"

services:
  app:
    build: .
    container_name: budget-app
    env_file:
      - .env
    volumes:
      - .:/opt/app
      - $VOLUME_PATH/media/:/opt/app/public/media
      - $VOLUME_PATH/app_tmp:/tmp
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    hostname: db
    image: postgres:11.4-alpine
    container_name: budget-db
    env_file:
      - .env
    volumes:
      - $VOLUME_PATH/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
